"""esquema inicial

Revision ID: 57577d1f1c12
Revises:
Create Date: 2026-09-05 06:03:32.993224
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "57577d1f1c12"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinicas_aliadas",
        sa.Column("nombre", sa.String(length=160), nullable=False),
        sa.Column("ciudad", sa.String(length=80), nullable=False),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("telefono", sa.String(length=32), nullable=True),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clinicas_aliadas")),
    )
    op.create_index(
        op.f("ix_clinicas_aliadas_ciudad"), "clinicas_aliadas", ["ciudad"], unique=False
    )
    op.create_table(
        "eventos_salientes",
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column(
            "datos",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("procesado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("intentos", sa.Integer(), nullable=False),
        sa.Column("ultimo_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eventos_salientes")),
    )
    op.create_index(
        op.f("ix_eventos_salientes_nombre"), "eventos_salientes", ["nombre"], unique=False
    )
    op.create_index(
        op.f("ix_eventos_salientes_procesado_en"),
        "eventos_salientes",
        ["procesado_en"],
        unique=False,
    )
    op.create_table(
        "planes",
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("ciudad", sa.String(length=80), nullable=True),
        sa.Column("valor_mensual", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cupos_mascotas", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_planes")),
        sa.UniqueConstraint("nombre", name=op.f("uq_planes_nombre")),
    )
    op.create_index(op.f("ix_planes_ciudad"), "planes", ["ciudad"], unique=False)
    op.create_table(
        "usuarios",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("nombre", sa.String(length=160), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("rol", sa.String(length=32), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuarios")),
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=True)
    op.create_table(
        "campanas",
        sa.Column("nombre", sa.String(length=160), nullable=False),
        sa.Column("canal", sa.String(length=24), nullable=False),
        sa.Column("plantilla", sa.String(length=120), nullable=True),
        sa.Column("contenido", sa.Text(), nullable=True),
        sa.Column(
            "segmento",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("estado", sa.String(length=24), nullable=False),
        sa.Column("programada_para", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creada_por_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creada_por_id"], ["usuarios.id"], name=op.f("fk_campanas_creada_por_id_usuarios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campanas")),
    )
    op.create_index(op.f("ix_campanas_estado"), "campanas", ["estado"], unique=False)
    op.create_table(
        "familias",
        sa.Column("titular_nombre", sa.String(length=160), nullable=False),
        sa.Column("documento", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("telefono", sa.String(length=32), nullable=False),
        sa.Column("ciudad", sa.String(length=80), nullable=False),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("latitud", sa.Float(), nullable=True),
        sa.Column("longitud", sa.Float(), nullable=True),
        sa.Column("estado", sa.String(length=32), nullable=False),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("usuario_portal_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["usuario_portal_id"],
            ["usuarios.id"],
            name=op.f("fk_familias_usuario_portal_id_usuarios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_familias")),
    )
    op.create_index(op.f("ix_familias_ciudad"), "familias", ["ciudad"], unique=False)
    op.create_index(op.f("ix_familias_documento"), "familias", ["documento"], unique=True)
    op.create_index(op.f("ix_familias_email"), "familias", ["email"], unique=False)
    op.create_index(op.f("ix_familias_estado"), "familias", ["estado"], unique=False)
    op.create_index(op.f("ix_familias_telefono"), "familias", ["telefono"], unique=False)
    op.create_table(
        "reglas_plan",
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("nombre", sa.String(length=160), nullable=False),
        sa.Column(
            "condicion",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "accion",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("prioridad", sa.Integer(), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["planes.id"],
            name=op.f("fk_reglas_plan_plan_id_planes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reglas_plan")),
    )
    op.create_table(
        "rutas",
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("ciudad", sa.String(length=80), nullable=False),
        sa.Column("responsable_id", sa.Uuid(), nullable=True),
        sa.Column("estado", sa.String(length=24), nullable=False),
        sa.Column("distancia_km", sa.Float(), nullable=True),
        sa.Column("duracion_min", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["responsable_id"], ["usuarios.id"], name=op.f("fk_rutas_responsable_id_usuarios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rutas")),
    )
    op.create_index(op.f("ix_rutas_ciudad"), "rutas", ["ciudad"], unique=False)
    op.create_index(op.f("ix_rutas_estado"), "rutas", ["estado"], unique=False)
    op.create_index(op.f("ix_rutas_fecha"), "rutas", ["fecha"], unique=False)
    op.create_table(
        "contratos",
        sa.Column("familia_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_renovacion", sa.Date(), nullable=False),
        sa.Column("valor_mensual", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("dia_corte", sa.Integer(), nullable=False),
        sa.Column("estado", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["familia_id"], ["familias.id"], name=op.f("fk_contratos_familia_id_familias")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["planes.id"], name=op.f("fk_contratos_plan_id_planes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contratos")),
    )
    op.create_index(op.f("ix_contratos_estado"), "contratos", ["estado"], unique=False)
    op.create_index(op.f("ix_contratos_familia_id"), "contratos", ["familia_id"], unique=False)
    op.create_index(
        op.f("ix_contratos_fecha_renovacion"), "contratos", ["fecha_renovacion"], unique=False
    )
    op.create_index(op.f("ix_contratos_plan_id"), "contratos", ["plan_id"], unique=False)
    op.create_table(
        "mascotas",
        sa.Column("familia_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("especie", sa.String(length=40), nullable=False),
        sa.Column("raza", sa.String(length=80), nullable=True),
        sa.Column("sexo", sa.String(length=16), nullable=True),
        sa.Column("fecha_nacimiento", sa.Date(), nullable=True),
        sa.Column("peso_kg", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["familia_id"],
            ["familias.id"],
            name=op.f("fk_mascotas_familia_id_familias"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mascotas")),
    )
    op.create_index(op.f("ix_mascotas_familia_id"), "mascotas", ["familia_id"], unique=False)
    op.create_table(
        "mensajes",
        sa.Column("familia_id", sa.Uuid(), nullable=True),
        sa.Column("canal", sa.String(length=24), nullable=False),
        sa.Column("direccion", sa.String(length=12), nullable=False),
        sa.Column("plantilla", sa.String(length=120), nullable=True),
        sa.Column("contenido", sa.Text(), nullable=True),
        sa.Column("estado", sa.String(length=24), nullable=False),
        sa.Column("id_externo", sa.String(length=120), nullable=True),
        sa.Column("enviado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("campana_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campana_id"], ["campanas.id"], name=op.f("fk_mensajes_campana_id_campanas")
        ),
        sa.ForeignKeyConstraint(
            ["familia_id"], ["familias.id"], name=op.f("fk_mensajes_familia_id_familias")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mensajes")),
    )
    op.create_index(op.f("ix_mensajes_campana_id"), "mensajes", ["campana_id"], unique=False)
    op.create_index(op.f("ix_mensajes_canal"), "mensajes", ["canal"], unique=False)
    op.create_index(op.f("ix_mensajes_estado"), "mensajes", ["estado"], unique=False)
    op.create_index(op.f("ix_mensajes_familia_id"), "mensajes", ["familia_id"], unique=False)
    op.create_index(op.f("ix_mensajes_id_externo"), "mensajes", ["id_externo"], unique=False)
    op.create_table(
        "cuotas",
        sa.Column("contrato_id", sa.Uuid(), nullable=False),
        sa.Column("periodo", sa.String(length=7), nullable=False),
        sa.Column("fecha_vencimiento", sa.Date(), nullable=False),
        sa.Column("valor", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("estado", sa.String(length=24), nullable=False),
        sa.Column("dias_mora", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contrato_id"], ["contratos.id"], name=op.f("fk_cuotas_contrato_id_contratos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cuotas")),
    )
    op.create_index(op.f("ix_cuotas_contrato_id"), "cuotas", ["contrato_id"], unique=False)
    op.create_index(op.f("ix_cuotas_estado"), "cuotas", ["estado"], unique=False)
    op.create_index(
        op.f("ix_cuotas_fecha_vencimiento"), "cuotas", ["fecha_vencimiento"], unique=False
    )
    op.create_index(op.f("ix_cuotas_periodo"), "cuotas", ["periodo"], unique=False)
    op.create_table(
        "servicios",
        sa.Column("familia_id", sa.Uuid(), nullable=False),
        sa.Column("mascota_id", sa.Uuid(), nullable=True),
        sa.Column("tipo", sa.String(length=24), nullable=False),
        sa.Column("estado", sa.String(length=32), nullable=False),
        sa.Column("programado_para", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ruta_id", sa.Uuid(), nullable=True),
        sa.Column("requiere_autorizacion", sa.Boolean(), nullable=False),
        sa.Column("autorizado", sa.Boolean(), nullable=False),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["familia_id"], ["familias.id"], name=op.f("fk_servicios_familia_id_familias")
        ),
        sa.ForeignKeyConstraint(
            ["mascota_id"], ["mascotas.id"], name=op.f("fk_servicios_mascota_id_mascotas")
        ),
        sa.ForeignKeyConstraint(["ruta_id"], ["rutas.id"], name=op.f("fk_servicios_ruta_id_rutas")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_servicios")),
    )
    op.create_index(op.f("ix_servicios_estado"), "servicios", ["estado"], unique=False)
    op.create_index(op.f("ix_servicios_familia_id"), "servicios", ["familia_id"], unique=False)
    op.create_index(op.f("ix_servicios_mascota_id"), "servicios", ["mascota_id"], unique=False)
    op.create_index(
        op.f("ix_servicios_programado_para"), "servicios", ["programado_para"], unique=False
    )
    op.create_index(op.f("ix_servicios_ruta_id"), "servicios", ["ruta_id"], unique=False)
    op.create_index(op.f("ix_servicios_tipo"), "servicios", ["tipo"], unique=False)
    op.create_table(
        "encuestas",
        sa.Column("servicio_id", sa.Uuid(), nullable=False),
        sa.Column("familia_id", sa.Uuid(), nullable=False),
        sa.Column("enviada_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("respondida_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("puntaje", sa.Integer(), nullable=True),
        sa.Column("comentario", sa.Text(), nullable=True),
        sa.Column("estado", sa.String(length=24), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["familia_id"], ["familias.id"], name=op.f("fk_encuestas_familia_id_familias")
        ),
        sa.ForeignKeyConstraint(
            ["servicio_id"], ["servicios.id"], name=op.f("fk_encuestas_servicio_id_servicios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_encuestas")),
    )
    op.create_index(op.f("ix_encuestas_estado"), "encuestas", ["estado"], unique=False)
    op.create_index(op.f("ix_encuestas_familia_id"), "encuestas", ["familia_id"], unique=False)
    op.create_index(op.f("ix_encuestas_servicio_id"), "encuestas", ["servicio_id"], unique=False)
    op.create_table(
        "eventos_preventivos",
        sa.Column("mascota_id", sa.Uuid(), nullable=False),
        sa.Column("tipo", sa.String(length=60), nullable=False),
        sa.Column("producto", sa.String(length=120), nullable=True),
        sa.Column("fecha_programada", sa.Date(), nullable=False),
        sa.Column("fecha_aplicacion", sa.Date(), nullable=True),
        sa.Column("proxima_fecha", sa.Date(), nullable=True),
        sa.Column("requiere_autorizacion", sa.Boolean(), nullable=False),
        sa.Column("autorizado", sa.Boolean(), nullable=False),
        sa.Column("servicio_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mascota_id"], ["mascotas.id"], name=op.f("fk_eventos_preventivos_mascota_id_mascotas")
        ),
        sa.ForeignKeyConstraint(
            ["servicio_id"],
            ["servicios.id"],
            name=op.f("fk_eventos_preventivos_servicio_id_servicios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eventos_preventivos")),
    )
    op.create_index(
        op.f("ix_eventos_preventivos_fecha_programada"),
        "eventos_preventivos",
        ["fecha_programada"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eventos_preventivos_mascota_id"),
        "eventos_preventivos",
        ["mascota_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eventos_preventivos_proxima_fecha"),
        "eventos_preventivos",
        ["proxima_fecha"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eventos_preventivos_tipo"), "eventos_preventivos", ["tipo"], unique=False
    )
    op.create_table(
        "historias_clinicas",
        sa.Column("mascota_id", sa.Uuid(), nullable=False),
        sa.Column("servicio_id", sa.Uuid(), nullable=True),
        sa.Column("profesional_id", sa.Uuid(), nullable=True),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("motivo", sa.Text(), nullable=False),
        sa.Column("anamnesis", sa.Text(), nullable=True),
        sa.Column("diagnostico", sa.Text(), nullable=True),
        sa.Column("tratamiento", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mascota_id"], ["mascotas.id"], name=op.f("fk_historias_clinicas_mascota_id_mascotas")
        ),
        sa.ForeignKeyConstraint(
            ["profesional_id"],
            ["usuarios.id"],
            name=op.f("fk_historias_clinicas_profesional_id_usuarios"),
        ),
        sa.ForeignKeyConstraint(
            ["servicio_id"],
            ["servicios.id"],
            name=op.f("fk_historias_clinicas_servicio_id_servicios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historias_clinicas")),
    )
    op.create_index(
        op.f("ix_historias_clinicas_fecha"), "historias_clinicas", ["fecha"], unique=False
    )
    op.create_index(
        op.f("ix_historias_clinicas_mascota_id"), "historias_clinicas", ["mascota_id"], unique=False
    )
    op.create_table(
        "pagos",
        sa.Column("cuota_id", sa.Uuid(), nullable=True),
        sa.Column("familia_id", sa.Uuid(), nullable=False),
        sa.Column("referencia_externa", sa.String(length=120), nullable=False),
        sa.Column("proveedor", sa.String(length=32), nullable=False),
        sa.Column("valor", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("estado", sa.String(length=24), nullable=False),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cuota_id"], ["cuotas.id"], name=op.f("fk_pagos_cuota_id_cuotas")),
        sa.ForeignKeyConstraint(
            ["familia_id"], ["familias.id"], name=op.f("fk_pagos_familia_id_familias")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pagos")),
    )
    op.create_index(op.f("ix_pagos_cuota_id"), "pagos", ["cuota_id"], unique=False)
    op.create_index(op.f("ix_pagos_estado"), "pagos", ["estado"], unique=False)
    op.create_index(op.f("ix_pagos_familia_id"), "pagos", ["familia_id"], unique=False)
    op.create_index(
        op.f("ix_pagos_referencia_externa"), "pagos", ["referencia_externa"], unique=True
    )
    op.create_table(
        "paradas_ruta",
        sa.Column("ruta_id", sa.Uuid(), nullable=False),
        sa.Column("servicio_id", sa.Uuid(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("latitud", sa.Float(), nullable=True),
        sa.Column("longitud", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ruta_id"],
            ["rutas.id"],
            name=op.f("fk_paradas_ruta_ruta_id_rutas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["servicio_id"], ["servicios.id"], name=op.f("fk_paradas_ruta_servicio_id_servicios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paradas_ruta")),
    )
    op.create_index(op.f("ix_paradas_ruta_ruta_id"), "paradas_ruta", ["ruta_id"], unique=False)
    op.create_index(
        op.f("ix_paradas_ruta_servicio_id"), "paradas_ruta", ["servicio_id"], unique=False
    )
    op.create_table(
        "pendientes",
        sa.Column("servicio_origen_id", sa.Uuid(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("requiere_autorizacion", sa.Boolean(), nullable=False),
        sa.Column("autorizado", sa.Boolean(), nullable=False),
        sa.Column("resuelto", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["servicio_origen_id"],
            ["servicios.id"],
            name=op.f("fk_pendientes_servicio_origen_id_servicios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pendientes")),
    )
    op.create_index(
        op.f("ix_pendientes_servicio_origen_id"), "pendientes", ["servicio_origen_id"], unique=False
    )
    op.create_table(
        "remisiones_aliadas",
        sa.Column("clinica_id", sa.Uuid(), nullable=False),
        sa.Column("servicio_id", sa.Uuid(), nullable=False),
        sa.Column("beneficio_aplicado", sa.String(length=120), nullable=True),
        sa.Column("valor_cubierto", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("estado", sa.String(length=24), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clinica_id"],
            ["clinicas_aliadas.id"],
            name=op.f("fk_remisiones_aliadas_clinica_id_clinicas_aliadas"),
        ),
        sa.ForeignKeyConstraint(
            ["servicio_id"],
            ["servicios.id"],
            name=op.f("fk_remisiones_aliadas_servicio_id_servicios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_remisiones_aliadas")),
    )
    op.create_index(
        op.f("ix_remisiones_aliadas_clinica_id"), "remisiones_aliadas", ["clinica_id"], unique=False
    )
    op.create_index(
        op.f("ix_remisiones_aliadas_estado"), "remisiones_aliadas", ["estado"], unique=False
    )
    op.create_index(
        op.f("ix_remisiones_aliadas_servicio_id"),
        "remisiones_aliadas",
        ["servicio_id"],
        unique=False,
    )
    op.create_table(
        "adjuntos_clinicos",
        sa.Column("historia_id", sa.Uuid(), nullable=False),
        sa.Column("nombre_archivo", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["historia_id"],
            ["historias_clinicas.id"],
            name=op.f("fk_adjuntos_clinicos_historia_id_historias_clinicas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adjuntos_clinicos")),
    )
    op.create_index(
        op.f("ix_adjuntos_clinicos_historia_id"), "adjuntos_clinicos", ["historia_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adjuntos_clinicos_historia_id"), table_name="adjuntos_clinicos")
    op.drop_table("adjuntos_clinicos")
    op.drop_index(op.f("ix_remisiones_aliadas_servicio_id"), table_name="remisiones_aliadas")
    op.drop_index(op.f("ix_remisiones_aliadas_estado"), table_name="remisiones_aliadas")
    op.drop_index(op.f("ix_remisiones_aliadas_clinica_id"), table_name="remisiones_aliadas")
    op.drop_table("remisiones_aliadas")
    op.drop_index(op.f("ix_pendientes_servicio_origen_id"), table_name="pendientes")
    op.drop_table("pendientes")
    op.drop_index(op.f("ix_paradas_ruta_servicio_id"), table_name="paradas_ruta")
    op.drop_index(op.f("ix_paradas_ruta_ruta_id"), table_name="paradas_ruta")
    op.drop_table("paradas_ruta")
    op.drop_index(op.f("ix_pagos_referencia_externa"), table_name="pagos")
    op.drop_index(op.f("ix_pagos_familia_id"), table_name="pagos")
    op.drop_index(op.f("ix_pagos_estado"), table_name="pagos")
    op.drop_index(op.f("ix_pagos_cuota_id"), table_name="pagos")
    op.drop_table("pagos")
    op.drop_index(op.f("ix_historias_clinicas_mascota_id"), table_name="historias_clinicas")
    op.drop_index(op.f("ix_historias_clinicas_fecha"), table_name="historias_clinicas")
    op.drop_table("historias_clinicas")
    op.drop_index(op.f("ix_eventos_preventivos_tipo"), table_name="eventos_preventivos")
    op.drop_index(op.f("ix_eventos_preventivos_proxima_fecha"), table_name="eventos_preventivos")
    op.drop_index(op.f("ix_eventos_preventivos_mascota_id"), table_name="eventos_preventivos")
    op.drop_index(op.f("ix_eventos_preventivos_fecha_programada"), table_name="eventos_preventivos")
    op.drop_table("eventos_preventivos")
    op.drop_index(op.f("ix_encuestas_servicio_id"), table_name="encuestas")
    op.drop_index(op.f("ix_encuestas_familia_id"), table_name="encuestas")
    op.drop_index(op.f("ix_encuestas_estado"), table_name="encuestas")
    op.drop_table("encuestas")
    op.drop_index(op.f("ix_servicios_tipo"), table_name="servicios")
    op.drop_index(op.f("ix_servicios_ruta_id"), table_name="servicios")
    op.drop_index(op.f("ix_servicios_programado_para"), table_name="servicios")
    op.drop_index(op.f("ix_servicios_mascota_id"), table_name="servicios")
    op.drop_index(op.f("ix_servicios_familia_id"), table_name="servicios")
    op.drop_index(op.f("ix_servicios_estado"), table_name="servicios")
    op.drop_table("servicios")
    op.drop_index(op.f("ix_cuotas_periodo"), table_name="cuotas")
    op.drop_index(op.f("ix_cuotas_fecha_vencimiento"), table_name="cuotas")
    op.drop_index(op.f("ix_cuotas_estado"), table_name="cuotas")
    op.drop_index(op.f("ix_cuotas_contrato_id"), table_name="cuotas")
    op.drop_table("cuotas")
    op.drop_index(op.f("ix_mensajes_id_externo"), table_name="mensajes")
    op.drop_index(op.f("ix_mensajes_familia_id"), table_name="mensajes")
    op.drop_index(op.f("ix_mensajes_estado"), table_name="mensajes")
    op.drop_index(op.f("ix_mensajes_canal"), table_name="mensajes")
    op.drop_index(op.f("ix_mensajes_campana_id"), table_name="mensajes")
    op.drop_table("mensajes")
    op.drop_index(op.f("ix_mascotas_familia_id"), table_name="mascotas")
    op.drop_table("mascotas")
    op.drop_index(op.f("ix_contratos_plan_id"), table_name="contratos")
    op.drop_index(op.f("ix_contratos_fecha_renovacion"), table_name="contratos")
    op.drop_index(op.f("ix_contratos_familia_id"), table_name="contratos")
    op.drop_index(op.f("ix_contratos_estado"), table_name="contratos")
    op.drop_table("contratos")
    op.drop_index(op.f("ix_rutas_fecha"), table_name="rutas")
    op.drop_index(op.f("ix_rutas_estado"), table_name="rutas")
    op.drop_index(op.f("ix_rutas_ciudad"), table_name="rutas")
    op.drop_table("rutas")
    op.drop_table("reglas_plan")
    op.drop_index(op.f("ix_familias_telefono"), table_name="familias")
    op.drop_index(op.f("ix_familias_estado"), table_name="familias")
    op.drop_index(op.f("ix_familias_email"), table_name="familias")
    op.drop_index(op.f("ix_familias_documento"), table_name="familias")
    op.drop_index(op.f("ix_familias_ciudad"), table_name="familias")
    op.drop_table("familias")
    op.drop_index(op.f("ix_campanas_estado"), table_name="campanas")
    op.drop_table("campanas")
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_planes_ciudad"), table_name="planes")
    op.drop_table("planes")
    op.drop_index(op.f("ix_eventos_salientes_procesado_en"), table_name="eventos_salientes")
    op.drop_index(op.f("ix_eventos_salientes_nombre"), table_name="eventos_salientes")
    op.drop_table("eventos_salientes")
    op.drop_index(op.f("ix_clinicas_aliadas_ciudad"), table_name="clinicas_aliadas")
    op.drop_table("clinicas_aliadas")
    # ### end Alembic commands ###
